name: ngx-file-upload/core

on: [push]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.8'

      - name: install dependencies
        run: |
          cd src
          npm i
          npm i puppeteer@chrome-78
          npm run webdriver:update

  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: lint
        run: |
          cd src
          npm run lint -- core

  unit-tests:
    needs: install
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1
      
      - name: build packages
        run: |
          cd src
          npm run build -- core

      - name: unit tests
        run: |
          cd src
          npm run github-actions:unit-tests-core

      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./src/coverage/core/lcov.info
          flags: core
